# Generated by Django 3.1.1 on 2020-10-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='full_name',
            new_name='name',
        ),
    ]
