# Generated by Django 3.1.1 on 2020-10-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0002_auto_20201022_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tier',
            new_name='Rarity',
        ),
    ]
