# Generated by Django 3.1.1 on 2020-11-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0003_auto_20201023_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TierList.rarity'),
        ),
    ]
