# Generated by Django 3.1.1 on 2020-12-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0006_auto_20201230_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TierList.element'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TierList.gender'),
        ),
        migrations.AlterField(
            model_name='character',
            name='nation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TierList.nation'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='TierList.weapon'),
        ),
    ]
