# Generated by Django 3.1.1 on 2021-01-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0007_auto_20201230_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='element',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='character',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
