# Generated by Django 3.1.1 on 2021-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TierList', '0009_auto_20210102_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nation',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='weapon',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
